### ISSUE TITLE
Doesn't load anymore

### ISSUE THREAD

**Issue by kensettle949** [PlummersSoftwareLLC/PrimeView#35]
Every reportnn.json is reporting a 404 error, so it just says "loading..." forever and never loads any results.

**Comment by kensettle949** [comment]
Seems fixed now. That was fast!

**Comment by rbergen** [comment]
I didn't change anything. :) To me, it looks like you experienced an initial glitch in loading the configuration JSON, which tells PrimeView to load benchmark results from the right place. Loading "reportnn.json" files is the fallback behavior that is only used if no configuration is available.

**Comment by kensettle949** [comment]
It's strange because I tried another browser and had the same issue, so I
assumed that it was happening on the server side.

Do you know if Dave is going to do anymore videos?

Thanks!

Sincerely,

Ken Settle

**Comment by rbergen** [comment]
The thing is that PrimeView is a full front-end application; all logic runs in the browser, so in that sense there is no server-side. Except for the fact that the (static) files need to be downloaded before it can run, of course. Maybe GitHub Pages, which is where the application is hosted, was having some kind of issue with serving out the configuration.json.

Concerning more videos from Dave, the last he told me on the topic was that he was indeed working on one. But I need to add that I know that he has quite a number of topics he likes and tries to cover in his videos, and timelines are never a topic of conversation between us.

**Comment by kensettle949** [comment]
Ok, thanks.
