### ISSUE TITLE
Common Lisp solution links are broken

### ISSUE THREAD

**Issue by surabax** [PlummersSoftwareLLC/PrimeView#69]
If you click on a solution link in PrimeView, you end up directed to a non-existent path like `https://github.com/PlummersSoftwareLLC/Primes/tree/drag-race/PrimeCommon%20Lisp/solution_2`, while the actual path in the repository is `https://github.com/PlummersSoftwareLLC/Primes/tree/drag-race/PrimeLisp/solution_2`. 

Either the link needs to be corrected in PrimeView or the path need to be changed in the repository.

**Comment by rbergen** [comment]
@surabax Good catch, thanks for reporting this! I've opened #70 to fix this.
